### ISSUE TITLE
Remove user picture under Modified By

### ISSUE THREAD

**Issue by sdinetz** [Northern-Block/NB_Fortis_Demo#12]

**Comment by shivakanyap** [comment]
Done

**Comment by sdinetz** [comment]
We are still seeing the picture on the File Repo screen in the Last Modified By column

**Comment by shivakanyap** [comment]
Done.
